version: '3.7'
services:
  camera:
    build:
      context: .
      dockerfile: docker/camera.Dockerfile
    depends_on:
      - db
    ports:
      - 8080:8080
  cron:
    build:
      context: .
      dockerfile: docker/cron.Dockerfile
    depends_on:
      - db
  db:
    image: mariadb/server:10.4
    environment:
      - MARIADB_DATABASE=ccio
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_USER=user
      - MARIADB_PASSWORD=password
    volumes:
      - ./sql/user.sql:/docker-entrypoint-initdb.d/user.sql
      - ./sql/framework.sql:/docker-entrypoint-initdb.d/framework.sql
